from os import makedirs
from os.path import exists, join
from pathlib import Path

from taskjournal.constants import PLACEHOLDER_HOME_WIFI, PLACEHOLDER_OFFICE_WIFI
from taskjournal.services.base import BaseService
from taskjournal.services.logger import logger

_HOLIDAYS_TEMPLATE = """\
# Holidays {year}
# Format: YYYY-MM-DD - Description
#
## Public holidays
# 2026-01-01 - New Year's Day

## Company holidays
# Add company-specific days here

## Personal days
# Add personal days off here
"""

_FIREMAN_TEMPLATE = """\
# Fireman weeks {year}
# Add one date per week you are on fireman duty (any day of that week).
# Format: YYYY-MM-DD
#
"""

ENV_PATH = Path.home() / ".config" / "taskjournal" / ".env"

_DEFAULTS = {
    "TEMPLATE_FORMAT": "md",
    "BASE_DIR": str(Path.home() / "Documents" / "DailyNotes"),
    "BACKUP_DIR": str(Path.home() / "Documents" / "Backup"),
    "JIRA_ORGANIZATION": "organization",
    "JIRA_EMAIL": "your-email@example.com",
    "JIRA_API_TOKEN": "your-jira-key",
    "JIRA_BOARD_ID": "your-jira-board-id",
    "GIT_HUB_TOKEN": "your-github-token",
    "GIT_HUB_ORGANIZATION_NAME": "your-github-organization",
    "OPENAI_API_KEY": "your-openai-api-key",
    "HOME_WIFI": PLACEHOLDER_HOME_WIFI,
    "OFFICE_WIFI": PLACEHOLDER_OFFICE_WIFI,
    "EDITOR_APP": "Obsidian",
}


class SetupService(BaseService):

    def load_existing(self) -> dict[str, str]:
        """Read current values from the .env file if it exists."""
        values: dict[str, str] = dict(_DEFAULTS)
        if not ENV_PATH.exists():
            return values
        try:
            for line in ENV_PATH.read_text().splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                values[key.strip()] = value.strip().strip('"')
        except Exception as e:
            logger.warning(f"Could not read existing config: {e}")
        return values

    def write_env(self, values: dict[str, str]) -> None:
        ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
        known_keys = set(_DEFAULTS.keys())
        lines = [
            "# taskjournal configuration — generated by wk setup\n",
            "\n",
            "# Paths\n",
            f'TEMPLATE_FORMAT={values["TEMPLATE_FORMAT"]}\n',
            f'BASE_DIR={values["BASE_DIR"]}\n',
            f'BACKUP_DIR={values["BACKUP_DIR"]}\n',
            "\n",
            "# Jira\n",
            f'JIRA_ORGANIZATION={values["JIRA_ORGANIZATION"]}\n',
            f'JIRA_EMAIL={values["JIRA_EMAIL"]}\n',
            f'JIRA_API_TOKEN={values["JIRA_API_TOKEN"]}\n',
            f'JIRA_BOARD_ID={values["JIRA_BOARD_ID"]}\n',
            "\n",
            "# GitHub\n",
            f'GIT_HUB_TOKEN={values["GIT_HUB_TOKEN"]}\n',
            f'GIT_HUB_ORGANIZATION_NAME={values["GIT_HUB_ORGANIZATION_NAME"]}\n',
            "\n",
            "# OpenAI\n",
            f'OPENAI_API_KEY={values["OPENAI_API_KEY"]}\n',
            "\n",
            "# WiFi location detection\n",
            f'HOME_WIFI={values["HOME_WIFI"]}\n',
            f'OFFICE_WIFI={values["OFFICE_WIFI"]}\n',
            "\n",
            "# Editor\n",
            f'EDITOR_APP={values["EDITOR_APP"]}\n',
        ]
        extra = {k: v for k, v in values.items() if k not in known_keys}
        if extra:
            lines.append("\n# Custom\n")
            for k, v in extra.items():
                lines.append(f"{k}={v}\n")
        ENV_PATH.write_text("".join(lines))
        logger.debug(f"Config written to {ENV_PATH}")

    def is_configured(self, key: str, values: dict[str, str]) -> bool:
        """Return True if the value differs from the placeholder default."""
        return values.get(key, "") not in ("", _DEFAULTS.get(key, ""))

    def create_data_files(self, base_dir: str, year: int) -> None:
        """Create holidays.md and fireman_weeks.md for the given year if missing."""
        files = {
            join(base_dir, str(year), "holidays", "holidays.md"): _HOLIDAYS_TEMPLATE.format(year=year),
            join(base_dir, str(year), "fireman", "fireman_weeks.md"): _FIREMAN_TEMPLATE.format(year=year),
        }
        for path, content in files.items():
            if exists(path):
                logger.debug(f"Already exists: {path}")
                continue
            makedirs(str(Path(path).parent), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"Created: {path}")
