[project]
name = "taskjournal"
version = "0.73.0"
description = "A Python project for tracking daily work tasks."
authors = [{name = "Enric Ballo", email = "enric.ballo@gmail.com"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.9.4",
    "typer>=0.15.2",
    "jira>=3.8.0",
    "pydantic>=2.11.3",
    "httpx>=0.28.1",
    "gidgethub>=5.4.0",
    "jinja2>=3.1.6",
    "dependency-injector>=4.41.0",
    "python-dotenv>=1.0.0",
    "click>=8.1.0",
]

[project.scripts]
wk = "taskjournal.cli.main:app"

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pytest>=8.3.4",
    "pytest-dotenv>=0.5.2",
    "freezegun>=1.5.1",
    "pytest-mock>=3.14.0",
    "pytest-cov>=6.0.0",
    "black>=25.1.0",
    "pre-commit>=4.2.0",
    "poethepoet>=0.36.0",
    "pytest-asyncio>=1.2.0",
    "respx>=0.22.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 88
target-version = ['py312']

[tool.mypy]
python_version = 3.12
ignore_missing_imports = true
strict = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["taskjournal"]
addopts = "--cov=taskjournal --cov-report=term-missing"
asyncio_default_fixture_loop_scope = "function"

[tool.poe.tasks]
format = "black ."
lint = "mypy taskjournal"
test = "pytest tests"
coverage = "pytest --cov=taskjournal --cov-config=.coveragerc --cov-report=xml tests/"
check = { sequence = ["format", "test", "coverage"] }
