sonar.projectKey=eballo_eballo
sonar.organization=catalunyamedieval
sonar.python.version=3.11
sonar.sources=taskjournal/
sonar.exclusions=**/__pycache__/**,**/*.md,**/tests/**
sonar.tests=tests/
sonar.test.inclusions=tests/**/*.py
sonar.coverage.exclusions=**/tests/**
# Tell SonarCloud where the coverage report is
sonar.python.coverage.reportPaths=coverage.xml
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
