name: Taskjournal CI Build

on:
  push:
    paths:
      - "taskjournal/**"
      - ".github/workflows/build.yaml"
    branches: [ "main" ]
  pull_request:
    paths:
      - "taskjournal/**"
      - ".github/workflows/build.yaml"
    branches: [ "main" ]
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  build:
    name: Test & SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Important for SonarCloud SCM data

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: taskjournal
        run: poetry install

      - name: Run checks with poe
        working-directory: taskjournal
        run: poetry run poe coverage

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v8
        with:
          projectBaseDir: taskjournal
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
